# Generated by Django 5.0.2 on 2024-02-22 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='shopapp/images/'),
        ),
        migrations.AlterField(
            model_name='user',
            name='direction',
            field=models.CharField(max_length=200),
        ),
    ]
