# Generated by Django 5.0.2 on 2024-03-06 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_product_image_alter_user_direction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='sum',
            field=models.IntegerField(null=True),
        ),
    ]
